services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
  management:
    build:
      context: .
      dockerfile: functions/Dockerfile
    environment:
      AzureWebJobsStorage: UseDevelopmentStorage=true
      DOTNET_ENVIRONMENT: Development
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      ManagementApi__Authentication__Mode: Development
      ManagementApi__Gateway__BaseUrl: http://gateway:8080
    depends_on:
      - gateway
    ports:
      - "7071:7071"
  acceptance:
    build:
      context: .
      dockerfile: tests/acceptance/Dockerfile
    depends_on:
      - gateway
      - management
    environment:
      RUST_LOG: info
      GATEWAY_BASE_URL: http://gateway:8080
      MANAGEMENT_BASE_URL: http://management:7071/api
      OPS_BEARER_TOKEN: dev-token
  opsconsole-tests:
    build:
      context: .
      dockerfile: opsconsole/Dockerfile.integration
    depends_on:
      - gateway
      - management
    environment:
      OPS_MANAGEMENT_BASE_URL: http://management:7071/api
      OPS_GATEWAY_BASE_URL: http://gateway:8080
      MANAGEMENT_BASE_URL: http://management:7071/api
      GATEWAY_BASE_URL: http://gateway:8080
      OPS_BEARER_TOKEN: dev-token
      OPS_TENANT_ID: console
