services:
  servicebus:
    build:
      context: .
      dockerfile: servicebus-emulator/Dockerfile
    ports:
      - "7075:7075"
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
      EA_SERVICE_BUS_NAMESPACE: emulator
      EA_SERVICE_BUS_QUEUE: ea-admin
      EA_SERVICE_BUS_POLICY: emulator
      EA_SERVICE_BUS_KEY: emulator
      EA_SERVICE_BUS_EMULATOR_BASE_URL: http://servicebus:7075/
    depends_on:
      - servicebus
  management:
    build:
      context: .
      dockerfile: functions/Dockerfile
    environment:
      AzureWebJobsStorage: UseDevelopmentStorage=true
      DOTNET_ENVIRONMENT: Development
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      ManagementApi__Authentication__Mode: Development
      ManagementApi__ServiceBus__EmulatorBaseUrl: http://servicebus:7075/
      ManagementApi__ServiceBus__AdminQueueName: ea-admin
    depends_on:
      - gateway
      - servicebus
    ports:
      - "7071:7071"
