services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
  acceptance:
    build:
      context: .
      dockerfile: tests/acceptance/Dockerfile
    depends_on:
      - gateway
    environment:
      RUST_LOG: info
